services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ./entrypoint-django.sh
    environment:
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@bublik.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - BUBLIK_UI_DOCS_DIR=${BUBLIK_UI_DOCS_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - SECURE_HTTP=${SECURE_HTTP:-False}
      - ENABLE_JSON_LOGS_PROXY=${ENABLE_JSON_LOGS_PROXY:-True}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_ADMINS=${EMAIL_ADMINS}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - static_data:/app/bublik/bublik/representation/static
      - logs_data:/app/bublik/logs
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: bublik
      POSTGRES_USER: bublik
      POSTGRES_PASSWORD: bublik
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: >
      watchfiles --filter python 'celery -A ${CELERY_APP} worker --max-tasks-per-child ${CELERYD_MAX_TASKS_PER_CHILD} --concurrency 1 -l ${CELERY_LOG_LEVEL}'
    entrypoint: ./entrypoint-celery.sh
    depends_on:
      - db
      - rabbitmq
    volumes:
      - logs_data:/app/bublik/logs
    environment:
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: celery -A ${CELERY_APP} flower --persistent=${FLOWER_PERSISTENT} --url_prefix=${FLOWER_URL_PREFIX}
    environment:
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
    ports:
      - 5555:5555
    depends_on:
      - django
      - db
      - redis
      - rabbitmq
    volumes:
      - flower_data:/data
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - URL_PREFIX=${URL_PREFIX}
    ports:
      - 80:80
    volumes:
      - ./nginx/templates/local:/etc/nginx/templates
      - static_data:/app/bublik/bublik/representation/static
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - URL_PREFIX=${URL_PREFIX}
    depends_on:
      - django
      - flower
      - bublik-ui

  bublik-ui:
    container_name: bublik-ui
    build:
      context: ./bublik-ui
      dockerfile: ./apps/bublik/Dockerfile.dev
    environment:
      - BASE_URL=${URL_PREFIX}/v2
    ports:
      - 4200:4200
    develop:
      watch:
        - action: sync
          path: ./bublik-ui
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./bublik-ui/package.json

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - MP_SMTP_TLS_REQUIRED=${MP_SMTP_TLS_REQUIRED:-false}

  te-log-server:
    container_name: te-log-server
    build:
      context: .
      dockerfile: Dockerfile
      target: log-server
    ports:
      - "4321:80"
    volumes:
      - te-logs:/home/te-logs:rw
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - TE_INSTALL=/app/te/build/inst
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
    restart: unless-stopped

volumes:
  te-logs:
  db_data:
  flower_data:
  static_data:
  logs_data:
