services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: >
      gunicorn bublik.wsgi:application
      --bind ${BUBLIK_BIND_GUNICORN}
      --limit-request-line 0
      --chdir ${BUBLIK_SRC}
      --workers ${BUBLIK_WORKERS}
      --timeout ${BUBLIK_TIMEOUT}
      --graceful-timeout ${BUBLIK_GRACEFUL_TIMEOUT}
      --log-file ${BUBLIK_LOG}
      --access-logfile ${BUBLIK_ACCESS_LOG}
      --log-level info
      --name "${BUBLIK_WEB_NAME}"
    environment:
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - SECURE_HTTP=${SECURE_HTTP:-False}
      - ENABLE_JSON_LOGS_PROXY=${ENABLE_JSON_LOGS_PROXY:-False}
      - BUBLIK_UI_DOCS_DIR=${BUBLIK_UI_DOCS_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
    expose:
      - 8000
    entrypoint: ./entrypoint-django.sh
    depends_on:
      - db
      - redis
    volumes:
      - ${BUBLIK_DOCKER_DATA_DIR}/django-logs:/app/bublik/logs
      - static_data:/app/bublik/bublik/representation/static
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8000${URL_PREFIX}/api/v2/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis
    image: redis
    volumes:
      - "redis_data:/data"
    expose:
      - 6379

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    expose:
      - 5672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: celery -A ${CELERY_APP} worker --max-tasks-per-child ${CELERYD_MAX_TASKS_PER_CHILD} --concurrency 1 -l ${CELERY_LOG_LEVEL}
    environment:
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
    entrypoint: /app/bublik/entrypoint-celery.sh
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ${BUBLIK_DOCKER_DATA_DIR}/django-logs:/app/bublik/logs:rw
    healthcheck:
      test: ["CMD-SHELL", "celery -A ${CELERY_APP} inspect ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: celery -A ${CELERY_APP} flower --persistent=${FLOWER_PERSISTENT} --url_prefix=${FLOWER_URL_PREFIX}
    environment:
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
      - PER_CONF_DIR=${PER_CONF_DIR}
      - SECRET_KEY=${SECRET_KEY}
      - URL_PREFIX=${URL_PREFIX}
      - BUBLIK_UI_DIR=${BUBLIK_UI_DIR}
      - BUBLIK_SRC=${BUBLIK_SRC}
      - TE_BASE=${TE_BASE}
      - TMPDIR=${TMPDIR}
      - BUBLIK_LOGDIR=${BUBLIK_LOGDIR}
      - BUBLIK_LOG=${BUBLIK_LOG}
      - BUBLIK_ACCESS_LOG=${BUBLIK_ACCESS_LOG}
      - MANAGEMENT_COMMANDS_LOG=${MANAGEMENT_COMMANDS_LOG}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_APP=${CELERY_APP}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_ACCEPT_CONTENT=${CELERY_ACCEPT_CONTENT}
      - CELERY_TASK_SERIALIZER=${CELERY_TASK_SERIALIZER}
      - CELERY_RESULT_SERIALIZER=${CELERY_RESULT_SERIALIZER}
      - CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS}
      - CELERYD_MAX_TASKS_PER_CHILD=${CELERYD_MAX_TASKS_PER_CHILD}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - FLOWER_PERSISTENT=${FLOWER_PERSISTENT}
      - FLOWER_PORT=${FLOWER_PORT}
      - FLOWER_URL_PREFIX=${FLOWER_URL_PREFIX}
      - REDIS_HOST=${REDIS_HOST}
      - BUBLIK_BIND_GUNICORN=${BUBLIK_BIND_GUNICORN}
      - BUBLIK_WORKERS=${BUBLIK_WORKERS}
      - BUBLIK_TIMEOUT=${BUBLIK_TIMEOUT}
      - BUBLIK_GRACEFUL_TIMEOUT=${BUBLIK_GRACEFUL_TIMEOUT}
      - BUBLIK_WEB_NAME=${BUBLIK_WEB_NAME}
    expose:
      - 5555
    depends_on:
      - django
      - db
      - redis
      - rabbitmq
    volumes:
      - ./:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5555/${FLOWER_URL_PREFIX}/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  te-log-server:
    container_name: te-log-server
    build:
      context: .
      dockerfile: Dockerfile
      target: log-server
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - TE_INSTALL=/app/te/build/inst
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
      - BUBLIK_FQDN=${BUBLIK_FQDN}
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
      - URL_PREFIX=${URL_PREFIX}
    volumes:
      - ${BUBLIK_DOCKER_DATA_DIR}/te-logs/logs:/home/te-logs/logs:rw
      - ${BUBLIK_DOCKER_DATA_DIR}/te-logs/incoming:/home/te-logs/incoming:rw
      - ${BUBLIK_DOCKER_DATA_DIR}/te-logs/bad:/home/te-logs/bad:rw
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - URL_PREFIX=${URL_PREFIX}
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - URL_PREFIX=${URL_PREFIX}
      - DOLLAR=${DOLLAR}
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
    expose:
      - ${BUBLIK_DOCKER_PROXY_PORT}
    ports:
      - ${BUBLIK_DOCKER_PROXY_PORT}:${BUBLIK_DOCKER_PROXY_PORT}
    volumes:
      - ./nginx/templates/prod:/etc/nginx/templates:ro
      - static_data:/app/bublik/bublik/representation/static
    depends_on:
      - django
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${BUBLIK_DOCKER_PROXY_PORT}${URL_PREFIX}/v2/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db_data:
  static_data:
  flower_data:
  redis_data:
