services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: python manage.py runserver ${BUBLIK_DOCKER_DJANGO_HOST}:${BUBLIK_DOCKER_DJANGO_PORT}
    entrypoint: ./entrypoint-django.sh
    network_mode: host
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  db:
    image: postgres
    environment:
      POSTGRES_DB: bublik
      POSTGRES_USER: bublik
      POSTGRES_PASSWORD: bublik

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    command: >
      watchfiles --filter python 'celery -A ${CELERY_APP} worker --max-tasks-per-child ${CELERYD_MAX_TASKS_PER_CHILD} --concurrency 1 -l ${CELERY_LOG_LEVEL}'
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - URL_PREFIX=${URL_PREFIX}
        - DOCS_URL=${DOCS_URL}
    develop:
      watch:
        - path: ./bublik
          action: sync
          target: /app/bublik
          ignore:
            - .venv
            - bublik-ui
        - path: ./bublik/requirements.txt
          action: rebuild

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - URL_PREFIX=${URL_PREFIX}
    depends_on:
      - bublik-ui

  bublik-ui:
    container_name: ${COMPOSE_PROJECT_NAME}-bublik-ui
    network_mode: host
    build:
      context: ./bublik-ui
      dockerfile: ./apps/bublik/Dockerfile.dev
    environment:
      - BASE_URL=${URL_PREFIX}/v2
    ## ports:
    ##  - ${BUBLIK_DOCKER_BUBLIK_UI_PORT}:4200
    develop:
      watch:
        - action: sync
          path: ./bublik-ui
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./bublik-ui/package.json

  mailpit:
    container_name: ${COMPOSE_PROJECT_NAME}-mailpit
    image: axllent/mailpit
    network_mode: host
    restart: unless-stopped
    ## ports:
    ##   - 8025:8025
    ##   - 1025:1025
    environment:
      - MP_SMTP_TLS_REQUIRED=${MP_SMTP_TLS_REQUIRED:-false}

  te-log-server:
    container_name: ${COMPOSE_PROJECT_NAME}-te-log-server
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      target: log-server
    volumes:
      - ${BUBLIK_DOCKER_DATA_DIR}/logs/logs:/home/te-logs/logs:rw
      - ${BUBLIK_DOCKER_DATA_DIR}/logs/incoming:/home/te-logs/incoming:rw
      - ${BUBLIK_DOCKER_DATA_DIR}/logs/bad:/home/te-logs/bad:rw
      - static_te_html:/app/te-logs-static
    restart: unless-stopped
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - BUBLIK_DOCKER_TE_LOG_SERVER_PORT=${BUBLIK_DOCKER_TE_LOG_SERVER_PORT}
      - TE_INSTALL=/app/te/build/inst
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - UMASK=${UMASK:-022}
      - BUBLIK_FQDN=${BUBLIK_FQDN}
      - BUBLIK_DOCKER_PROXY_PORT=${BUBLIK_DOCKER_PROXY_PORT}
      - URL_PREFIX=${URL_PREFIX}
